Fix crash on kp analyzer
The commit includes test which broke analyzer previously. These include
dots and dashes. However these things do work sometimes and sometimes
not.

I mean while I'm not sure I'm feeding the data correctly, but I think crash
is bad idea anyway.

The crash was:

```
thread 'main' panicked at 'assertion failed: word_len >= self.min_reminder_length', target/.cargo/git/checkouts/rsmorphy-16a9b60a66c15c48/a6d43b
2/src/analyzer/units/by_analogy/kp.rs:87:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:445
   6: <rsmorphy::analyzer::units::by_analogy::kp::KnownPrefixAnalyzer as rsmorphy::analyzer::units::abc::AnalyzerUnit>::parse
             at target/.cargo/git/checkouts/rsmorphy-16a9b60a66c15c48/a6d43b2/src/analyzer/units/by_analogy/kp.rs:87
             at target/.cargo/git/checkouts/rsmorphy-16a9b60a66c15c48/a6d43b2/src/analyzer/units/by_analogy/kp.rs:40
   7: rsmorphy::analyzer::morph::MorphAnalyzer::parse
             at target/.cargo/git/checkouts/rsmorphy-16a9b60a66c15c48/a6d43b2/src/analyzer/morph.rs:90
             at target/.cargo/git/checkouts/rsmorphy-16a9b60a66c15c48/a6d43b2/src/analyzer/morph.rs:100
   8: <rsmorphy::analyzer::units::by_hyphen::hsp::HyphenSeparatedParticleAnalyzer as rsmorphy::analyzer::units::abc::AnalyzerUnit>::parse
             at target/.cargo/git/checkouts/rsmorphy-16a9b60a66c15c48/a6d43b2/src/analyzer/units/by_hyphen/hsp.rs:56
   9: rsmorphy::analyzer::morph::MorphAnalyzer::parse
             at target/.cargo/git/checkouts/rsmorphy-16a9b60a66c15c48/a6d43b2/src/analyzer/morph.rs:84
             at target/.cargo/git/checkouts/rsmorphy-16a9b60a66c15c48/a6d43b2/src/analyzer/morph.rs:100
```